### ISSUE TITLE
如何获取进来的人

### ISSUE THREAD

**Issue by 2547881370** [huangpd/kuaishou_live#1]
大大,获取进来的人有示例吗

**Comment by huangpd** [comment]
![image](https://github.com/huangpd/kuaishou_live/assets/29889615/dcbb8e00-fc62-428e-9d42-c0c5e6dd375b)

**Comment by 2547881370** [comment]
> ![image](https://private-user-images.githubusercontent.com/29889615/345268343-dcbb8e00-fc62-428e-9d42-c0c5e6dd375b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5NzY3MzAsIm5iZiI6MTcxOTk3NjQzMCwicGF0aCI6Ii8yOTg4OTYxNS8zNDUyNjgzNDMtZGNiYjhlMDAtZmM2Mi00MjhlLTlkNDItYzBjNWU2ZGQzNzViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDAzMTM1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4ZDdkZDU3NmMyNzVjMGE1NDhkYWMzMzEyMTc2YWJmNGQ3MzY3N2JjNWNlMzNhYWExZmUwOTlmZTgyNzg0YTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7qH2Z3HIuGUr-cVtIOj8503a2iHmSFMrIGq4mzcK9ds)

大大有代码示例吗

**Comment by huangpd** [comment]
代码跑起来就行了

**Comment by 2547881370** [comment]
![image](https://github.com/huangpd/kuaishou_live/assets/52987726/d5576d47-994d-4cf7-9a9c-1da55b0ba8f7)
大大,我把所有能解析的数据都打印了出来, 没有看到能获取到进来的人的消息

**Comment by huangpd** [comment]
> ![image](https://private-user-images.githubusercontent.com/52987726/345338949-d5576d47-994d-4cf7-9a9c-1da55b0ba8f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMDgzODIsIm5iZiI6MTcyMDAwODA4MiwicGF0aCI6Ii81Mjk4NzcyNi8zNDUzMzg5NDktZDU1NzZkNDctOTk0ZC00Y2Y3LTlhOWMtMWRhNTViMGJhOGY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDEyMDEyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhODBkYjNjNjMzMzVkYjEzOWNiZWU1OWM5YmZmYTAzM2Q1ZWUxYThkYmQ1NDZmM2ZhNGJiZjExNWViYjAyMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dtvpy2NT2eJUXiesQt83TVgUokMSEP0Wma1MA2lzMJw) 大大,我把所有能解析的数据都打印了出来, 没有看到能获取到进来的人的消息

那可能就没有吧

**Comment by huangpd** [comment]
> ![image](https://private-user-images.githubusercontent.com/52987726/345338949-d5576d47-994d-4cf7-9a9c-1da55b0ba8f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMDg4MTAsIm5iZiI6MTcyMDAwODUxMCwicGF0aCI6Ii81Mjk4NzcyNi8zNDUzMzg5NDktZDU1NzZkNDctOTk0ZC00Y2Y3LTlhOWMtMWRhNTViMGJhOGY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDEyMDgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzMDRmMGVkYTdmNGM4OTNmNGQzZjJiNDc3OTZjMWY3MjA4MTFlN2E1MTczODllMzhiZGZkNWI3YmRiMzMxNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9FSOLRxMZgvQb_w7m00yTi_MysTPOVQSWPjb-ariaqk) 大大,我把所有能解析的数据都打印了出来, 没有看到能获取到进来的人的消息

找些直播间有人的
